### ISSUE TITLE
메인화면 - 홈 Fragment 구현

### ISSUE THREAD

**Issue by jiwon2724** [jiwon2724/nearbook-android#4]
## Description
![image](https://user-images.githubusercontent.com/70135188/221398680-0d629277-9cf4-40b3-a46c-c763142f949b.png)
"홈"화면에 들어가는 기능을 구현한다.

## Todo
- [ ] 정해놓은 목표 달성률 표시
- [ ] 책 읽은 기록 잔디로 표시
- [ ] 현재 읽고 있는 책 표시

## ETC
기타사항
